# backend/analytics-service/cloudbuild.yaml
# CI/CD para Analytics Service en Google Cloud

steps:
  # ============================================================
  # STEP 1: Build de la imagen Docker
  # ============================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/analytics-service:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/analytics-service:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'backend/analytics-service'

  # ============================================================
  # STEP 2: Push de la imagen a Container Registry
  # ============================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/analytics-service:$COMMIT_SHA'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/analytics-service:latest'
    waitFor: ['build-image']

  # ============================================================
  # STEP 3: Escaneo de vulnerabilidades
  # ============================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'scan-image'
    args:
      - 'container'
      - 'images'
      - 'scan'
      - 'gcr.io/$PROJECT_ID/analytics-service:$COMMIT_SHA'
    waitFor: ['push-image']
    allowFailure: true

  # ============================================================
  # STEP 4: Deploy a Cloud Run
  # ============================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - 'analytics-service'
      - '--image=gcr.io/$PROJECT_ID/analytics-service:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--port=8080'
      - '--timeout=300'
      - '--concurrency=80'
      # Variables de entorno públicas
      # IMPORTANTE: En Cloud Run, NO se debe configurar GOOGLE_APPLICATION_CREDENTIALS
      # cuando se usa la identidad del servicio (service account). Cloud Run automáticamente
      # usa Application Default Credentials (ADC) con la cuenta de servicio especificada.
      - '--set-env-vars=NODE_ENV=production,PORT=8080,LOG_LEVEL=info,FIRESTORE_PROJECT_ID=$PROJECT_ID'
      # VPC para comunicación privada
      - '--vpc-connector=projects/$PROJECT_ID/locations/europe-west1/connectors/musicstream-connector'
      - '--vpc-egress=all-traffic'
      # Service Account con acceso a Firestore
      # IMPORTANTE: Esta cuenta de servicio debe tener el rol "roles/datastore.user" para Firestore
      # Para verificar: gcloud projects get-iam-policy $PROJECT_ID --flatten="bindings[].members" --filter="bindings.members:serviceAccount:analytics-service@$PROJECT_ID.iam.gserviceaccount.com"
      # Para asignar: gcloud projects add-iam-policy-binding $PROJECT_ID --member="serviceAccount:analytics-service@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/datastore.user"
      - '--service-account=analytics-service@$PROJECT_ID.iam.gserviceaccount.com'
    waitFor: ['push-image', 'scan-image']

  # ============================================================
  # STEP 5: Health Check post-deploy
  # ============================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe analytics-service \
          --region=europe-west1 \
          --format='value(status.url)')
        echo "Service URL: $SERVICE_URL"
        sleep 15
        curl -f "$SERVICE_URL/health" || exit 1
    waitFor: ['deploy-cloud-run']

# ============================================================
# Configuración de imágenes
# ============================================================
images:
  - 'gcr.io/$PROJECT_ID/analytics-service:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/analytics-service:latest'

# ============================================================
# Opciones adicionales
# ============================================================
timeout: 1200s

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'

substitutions:
  _SERVICE_NAME: 'analytics-service'
  _REGION: 'europe-west1'